### ISSUE TITLE
Thank you very much for your FTFlash program, it helped me a lot

### ISSUE THREAD

**Issue by alex-kerner-ext-orion** [swharden/SWHarden.com#12]
Thank you very much for your FTFlash program, it helped me a lot! 😄 
I wish you good and stable health.

![20230901_204840](https://github.com/swharden/SWHarden.com/assets/95759482/87e4ffc2-fe78-404e-b27f-daf74ff357f7)

**Comment by swharden** [comment]
Hi @alex-kerner-ext-orion, I'm so happy you enjoyed this app! I made it for a one-off project last week and I'm surprised to see that someone else is using it already! The internet is an awesome place 🚀 

I see the issues you opened on https://github.com/swharden/FTFlash/issues and I'll address those shortly 👍
