### ISSUE TITLE
Feedback on `Using Llama 2 to Answer Questions About Local Documents`

### ISSUE THREAD

**Issue by Oscar123456780** [swharden/SWHarden.com#17]
Regarding https://swharden.com/blog/2023-07-30-ai-document-qa/ 

Feedback goes here...

I loved your article! Just what I needed!

I’m creating a school-friendly AI for my school which can be fed audio (transcript by OpenAI’s whisper which is free) and txt docs. Any advice? I plan to have Python scripts that can be triggered via an Electron framework application.

**Comment by swharden** [comment]
Hi @Oscar123456780, I'm happy you found the article useful!

I haven't explored this topic much more beyond what I discovered and wrote on that page, so I'm afraid I don't have tons of advice there. I see HuggingFace has a Discord https://discord.com/invite/hugging-face-879548962464493619 maybe the group there can offer better suggestions based on them having more personal experience working with these models and document ingestion.

Hope it helps! Good luck! 🚀
