### ISSUE TITLE
Feedback on `Exponential Fit with Python`

### ISSUE THREAD

**Issue by Candice3PO** [swharden/SWHarden.com#28]
Regarding https://swharden.com/blog/2020-09-24-python-exponential-fit/ 

Hello, I find your explaination very useful, thanks!

Can you also clarify what Tau stands for?

Thanks!

**Comment by swharden** [comment]
Hi @Candice3PO, tau is the time constant

* https://en.wikipedia.org/wiki/Exponential_decay
* https://en.wikipedia.org/wiki/Time_constant
* https://www.teledynelecroy.com/doc/measuring-exponential-time-constant

Hope it helps!
Scott

**Comment by swharden** [comment]
From https://en.wikipedia.org/wiki/Exponential_decay another term for tau could be "exponential decay constant"

![image](https://github.com/swharden/SWHarden.com/assets/4165489/7b87f1e9-5a8f-416b-97c9-251654815088)
